# Creation date : 18.03.2024
# Created by : ESZ
# Description : This Compose file creates 2 containers mysql, phpmyadmin
# 
version: '2'

services:
    db:
        image: mysql:8.0.30
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
            MYSQL_DATABASE: db_flashcards
        restart: always
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: PHP_MY_ADMIN
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80

# The database will be persistent among containers restarts.
volumes:
    dbdata:


  
